
title: "Доктор Стафий"
description: "Эндокринолог и нутрициолог Стафий Диана Викторовна"
baseurl: ""
url: "https://doctorstafiy.ru"
remote_theme: https://github.com/zerostaticthemes/jekyll-serif-theme
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
