
title: "Доктор Стафий"
baseurl: "/"
url: "https://gosubv.github.io/doctorstafij/"
remote_theme: https://github.com/zerostaticthemes/jekyll-serif-theme
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
